app = "aladin-grib-adria"

[env]
  OUTDIR = "/data"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
